version: '3.2'
services:
  main:
    hostname: main.local
    build:
      context: ../
      dockerfile: docker/devcontainer/Dockerfile
    env_file: .env
    volumes:  # docker-compose.yml があるディレクトリからの相対パスで指定する
      - ..:/llm-work:cached
      - ~/.aws:/home/vscode/.aws:cached
      - ~/.ssh:/home/vscode/.ssh:cached
      - ~/.docker:/home/vscode/.docker:cached
    command: sleep infinity
    networks:
      br-llm-work:
        ipv4_address: 192.168.51.10

networks:
  br-llm-work:
    name: br-llm-work
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.51.0/24